server:
  port: 9191
spring:
  application:
    name: APIGATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**

        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**

        - id: ORGANIZATION-SERVICE
          uri: lb://ORGANIZATION-SERVICE
          predicates:
            - Path=/api/organizations/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
