server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  #remove the springBoot banner
  main:
    banner-mode: off

  application:
    name: EMPLOYEE-SERVICE

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#remove clear all unwanted output
logging:
  level:
    root: warn

#eureka server connection
#eureka:
#    service-url:
#      defaultZone: http://localhost:8761/eureka


#actuator endpoint for circuit breaker
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always


#circuit breaker configurations
resilience4j:
  circuitbreaker:
    instances:
      EMPLYOEE-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

#retry configurations

  retry:
    instances:
      EMPLYOEE-SERVICE:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 1s
