server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organization_db?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  #remove the springBoot banner
  main:
    banner-mode: off

  application:
    name: ORGANIZATION-SERVICE

#remove clear all unwanted output
logging:
  level:
    root: warn

#eureka server connection

#eureka:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

